apiVersion: v1
kind: Pod
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  containers:
    - image: laravelfans/laravel:6
      name: laravel-app
      ports:
      - containerPort: 8000
      env:
      - name: APP_ENV
        value: local
      envFrom:
      - secretRef:
          name: laravel-secret        
      

